[0;33m--- esp-idf-monitor 1.2.1 on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081460: call_start_cpu1 at /home/comfi/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[0;33m0x40088481: xt_utils_compare_and_set at /home/comfi/esp/esp-idf/components/xtensa/include/xt_utils.h:222
 (inlined by) esp_cpu_compare_and_set at /home/comfi/esp/esp-idf/components/esp_hw_support/cpu.c:483
[0m
[0;33m0x4000c2e0: memcpy in ROM
[0m
[0;33m0x4000c2f6: memcpy in ROM
[0m
[0;33m0x4008847e: xt_utils_compare_and_set at /home/comfi/esp/esp-idf/components/xtensa/include/xt_utils.h:215
 (inlined by) esp_cpu_compare_and_set at /home/comfi/esp/esp-idf/components/esp_hw_support/cpu.c:483
[0m
[0;33m0x4008dc79: spinlock_acquire at /home/comfi/esp/esp-idf/components/esp_hw_support/include/spinlock.h:130
 (inlined by) xPortEnterCriticalTimeout at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:501
[0m
[0;33m0x4008b817: vPortEnterCritical at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:589
 (inlined by) xQueueReceive at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1495
[0m
[0;33m0x4013c3ff: sys_arch_mbox_fetch at /home/comfi/esp/esp-idf/components/lwip/port/freertos/sys_arch.c:317
[0m
[0;33m0x4012b01c: tcpip_timeouts_mbox_fetch at /home/comfi/esp/esp-idf/components/lwip/lwip/src/api/tcpip.c:104
[0m
[0;33m0x4012b0de: tcpip_thread at /home/comfi/esp/esp-idf/components/lwip/lwip/src/api/tcpip.c:142
[0m
[0;33m0x4008da25: vPortTaskWrapper at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162
[0m
[0;33m0x40088572: esp_cpu_wait_for_intr at /home/comfi/esp/esp-idf/components/esp_hw_support/cpu.c:145
[0m
[0;33m0x400853a8: ipc_task at /home/comfi/esp/esp-idf/components/esp_system/esp_ipc.c:48
[0m
[0;33m0x4008856f: xt_utils_wait_for_intr at /home/comfi/esp/esp-idf/components/xtensa/include/xt_utils.h:81
 (inlined by) esp_cpu_wait_for_intr at /home/comfi/esp/esp-idf/components/esp_hw_support/cpu.c:132
[0m
[0;33m0x400d36d7: esp_vApplicationIdleHook at /home/comfi/esp/esp-idf/components/esp_system/freertos_hooks.c:59
[0m
[0;33m0x4008bead: prvIdleTask at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4170 (discriminator 1)
[0m
[0;33m0x4008da25: vPortTaskWrapper at /home/comfi/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162
[0m
[0;33m0x40080400: _init at ??:?
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0mException in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 76, in run
    data = self.serial.read(self.serial.in_waiting or 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 83, in run
    self.close_serial()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/comfi/.espressif/python_env/idf5.2_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error
[0m
